name: Pipeline


on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
        types: [opened, synchronize]

jobs:

    build:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 16
            - name: Install dependencies
              run: npm ci
            - name: Build app
              run: npm run build

    lint:
        needs: [build]
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/
            - uses: actions/setup-node@v3
              with:
                node-version: 16
            - name: Install dependencies
              run: npm ci
            - name: Pass lint
              run: npm run lint

    
