name: Pipeline


on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
        types: [opened, synchronize]

jobs:

    build:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 16
            - name: Install dependencies
              run: npm ci
            - name: Build app
              run: npm run build

    publish:
        runs-on: ubuntu-20.04
        permissions:
            contents: read
            deployments: write
        name: Publish to Cloudflare Pages
        steps:
            - uses: actions/checkout@v3
            - name: Publish to Cloudflare Pages
              uses: cloudflare/pages-action@v1
              with:
                apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                accountId: de1b1e4efab211c11794d0d9f6f577c3
                projectName: image-uploader
                directory: /.svelte-kit/cloudflare
                gitHubToken: ${{ secrets.GITHUB_TOKEN }}
                branch: main
                workingDirectory: /
                wranglerVersion: '3'
                
    
    

    
